
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package common;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int GE = 34;
  public static final int SEMI = 25;
  public static final int INT = 5;
  public static final int MINUS = 27;
  public static final int WRITE = 10;
  public static final int NOT = 32;
  public static final int AND = 30;
  public static final int LT = 35;
  public static final int RPAR = 22;
  public static final int OR = 31;
  public static final int BOOL = 7;
  public static final int COMMA = 24;
  public static final int FI = 18;
  public static final int DIV = 29;
  public static final int FLOAT_CONST = 42;
  public static final int PLUS = 26;
  public static final int ASSIGN = 14;
  public static final int MAIN = 4;
  public static final int IF = 16;
  public static final int ID = 44;
  public static final int LE = 36;
  public static final int EOF = 0;
  public static final int RETURN = 46;
  public static final int OD = 12;
  public static final int INT_CONST = 41;
  public static final int TRUE = 39;
  public static final int error = 1;
  public static final int NULL = 45;
  public static final int VOID = 9;
  public static final int EQ = 37;
  public static final int TIMES = 28;
  public static final int COLON = 23;
  public static final int ELSE = 19;
  public static final int READ = 13;
  public static final int CORP = 3;
  public static final int WHILE = 15;
  public static final int FLOAT = 6;
  public static final int THEN = 17;
  public static final int NE = 38;
  public static final int LPAR = 21;
  public static final int PROC = 2;
  public static final int STRING = 8;
  public static final int FALSE = 40;
  public static final int STRING_CONST = 43;
  public static final int GT = 33;
  public static final int ELIF = 20;
  public static final int DO = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROC",
  "CORP",
  "MAIN",
  "INT",
  "FLOAT",
  "BOOL",
  "STRING",
  "VOID",
  "WRITE",
  "DO",
  "OD",
  "READ",
  "ASSIGN",
  "WHILE",
  "IF",
  "THEN",
  "FI",
  "ELSE",
  "ELIF",
  "LPAR",
  "RPAR",
  "COLON",
  "COMMA",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "AND",
  "OR",
  "NOT",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "TRUE",
  "FALSE",
  "INT_CONST",
  "FLOAT_CONST",
  "STRING_CONST",
  "ID",
  "NULL",
  "RETURN"
  };

}

